language: r
cache: packages
matrix:
  include:
  - r: oldrel
    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
r_packages: covr
services: docker
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libgit2; fi
after_success:
 - R -e 'covr::codecov()'
