add_header <- function(lines, header) {
  if (length(lines) > 0) {
    c(header, lines, "")
  } else {
    c()
  }
}

#' Convert a Dockerfile to a Singularity recipe
#'
#' @param dockerfile The path of the Dockerfile
#' @param singularityrecipe The path of the Singularity recipe to be created
#' @param bootstrap Where to bootstrap the Singularity image from
#' @param header Add a header to the Singularity recipe
#'
#' @importFrom stringr str_replace_all str_subset
#' @importFrom readr read_lines write_lines
#'
#' @export
convert_dockerfile_to_singularityrecipe <- function(
  dockerfile,
  singularityrecipe,
  bootstrap = c("shub", "docker"),
  header = TRUE
) {
  bootstrap <- match.arg(bootstrap)

  # read docker file, detect commands with newlines
  lines <-
    readr::read_lines(dockerfile) %>%
    str_replace_all("# .*", "") %>%
    discard(function(x) grepl("^ *$", x)) %>%
    paste(collapse = "\n") %>%
    str_replace_all(" *\\\\\n *", " <NEWLINEPLACEHOLDER>") %>%
    strsplit("\n") %>%
    first()

  # parse earch section
  from <- str_subset(lines, "^FROM ") %>% str_replace_all("FROM ", "From: ")
  environment <- str_subset(lines, "^ENV ") %>% str_replace_all("ENV ", "    export ") %>% add_header("%environment")
  labels <- str_subset(lines, "^LABEL ") %>% str_replace_all("LABEL ", "    ") %>% add_header("%labels")
  files <- str_subset(lines, "^ADD ") %>% str_replace_all("ADD ", "    ") %>% add_header("%files")
  runscript <- str_subset(lines, "^ENTRYPOINT ") %>% str_replace_all("ENTRYPOINT ", "    exec ") %>% add_header("%runscript")

  # add commands for each mount because shub will otherwise the files are non-readable
  mounts <- files %>% str_subset("^[^%]") %>% str_replace_all(" *[^ ]* *([^ ]*) *", "\\1")
  extra_commands <- paste0(
    "    chmod -R 755 ", paste0("'", mounts, "'", collapse = " ")
  )

  # create post section
  post <- str_subset(lines, "^RUN ") %>% str_replace_all("RUN ", "    ") %>% c(extra_commands, .) %>% add_header("%post")

  # determine header
  if (header) {
    header <- c(
      "#######################################################################################",
      "## DO NOT EDIT THIS FILE! This file was automatically generated from the dockerfile. ##",
      "## Run babelfish::convert_dockerfile_to_singularityrecipe() to update this file.     ##",
      "#######################################################################################",
      ""
    )
  } else {
    header <- c()
  }

  # create recipe
  output <- c(
    header,
    paste0("Bootstrap: ", bootstrap),
    "",
    from,
    "",
    environment,
    labels,
    files,
    post,
    runscript
  ) %>%
    str_replace_all("<NEWLINEPLACEHOLDER>", "\\\\\n      ")

  # write to file
  readr::write_lines(output, singularityrecipe)
}
